# Defines which compose version to use
version: "3"

# Services line define which Docker images to run. In this case, it will be MySQL server and WordPress image.
services:
  db:
    # image: mysql:5.7 indicates the MySQL database container image from Docker Hub used in this installation.
    image: mysql:5.7
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    environment:
      # below four lines define the main variables needed for the MySQL container to work: database, database username, database user password, and the MySQL root password.
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: bloghub
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: password
    networks:
      - wpsite

  # phpmyadmin
  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - "8010:80"
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: password
    networks:
      - wpsite
  # Wordpress
  wordpress:
    depends_on:
      - db
    image: wordpress:latest
    restart: always
    # Restart line controls the restart mode, meaning if the container stops running for any reason, it will restart the process immediately.
    ports:
      - "8000:80"
      # The previous line defines the port that the WordPress container will use. After successful installation, the full path will look like this: http://localhost:8000
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_NAME: bloghub
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: password
# Similar to MySQL image variables, the last four lines define the main variables needed for the WordPress container to work properly with the MySQL container.
    volumes: ["./:/var/www/html"]
    networks:
      - wpsite
networks:
  wpsite:
volumes:
 db_data:
